---
- hosts: all
  gather_facts: False
  connection: local
  remote_user: "{{ lookup('env','USER') }}"
  tasks: 
  - name: Find the vm folder
    vmware_guest_find:
      hostname: "{{ hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      validate_certs: False
      name: "{{ inventory_hostname }}"
    delegate_to: localhost
    register: vm_folder
    tags: find_folder

  - name: Find VM_Folder Task
    debug: var=vm_folder
    tags: find_folder

  - name: Take snapshot of all VM's found in variable machines.
    vmware_guest_snapshot:
      datacenter: "{{ datacenter }}"
      hostname: "{{ hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      validate_certs: False
      folder: "{{ vm_folder }}"
      name: "{{ inventory_hostname }}"
      state: present
      snapshot_name: "{{ snapshot_name }}"
      description: "{{ snapshot_description }}"
    delegate_to: localhost
    register: vm 

  - name: Create a status file
    file:
      path: "/tmp/snapshot_creation_status_{{ lookup('env','USER') }}_{{lookup ('pipe','date +%Y-%m-%d') }}"
      state: touch
      mode: 0744
    delegate_to: localhost

  - name: Adding snapshot created servers to status file
    lineinfile:
      dest: "/tmp/snapshot_creation_status_{{ lookup('env','USER') }}_{{lookup ('pipe','date +%Y-%m-%d') }}"
      line: "{{ inventory_hostname }}"
    when: vm.changed == True
    delegate_to: localhost

  - name: Sending Email
    mail:
      subject: Snapshot Creation Status
      to:
         - mymail@organization.com
         - peter@ABCcompany.com
      attach:
      - "/tmp/snapshot_creation_status_{{ lookup('env','USER') }}_{{lookup ('pipe','date +%Y-%m-%d') }}"
      body: " Hi Team,\n\nSnapshots have been created for the servers attached with this email.\n"
    delegate_to: localhost
    run_once: True
