---
- hosts: all
  remote_user: "{{ lookup('env','USER') }}"
  become: true
  become_user: root
  gather_facts: True
  tasks:
    - name: Install and update security patches
      yum:
        name: '*'
        state: latest
      register: updatesecurity
      ignore_errors: true

    - name: Reboot the server
      reboot:
        test_command: uptime

    - name: Get server hostname
      command: hostname
      register: host_name
      tags: post_check

    - name: Get running current running kernel
      command: uname -r
      register: run_kern
      tags: post_check

    - name: Get server uptime
      command: uptime |awk '{print $3,$4}'
      register: up_time
      tags: post_check

    - name: copy the output to newfile
      lineinfile:
        dest: "/tmp/kern_val_{{ lookup('env','USER') }}_{{ lookup('pipe', 'date +%Y-%m-%d-%H-%M-%S') }}"
        create: "yes"
        line: "{{host_name.stdout, run_kern.stdout, up_time.stdout }}"
      delegate_to: "127.0.0.1"
      tags: post_check
